import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service - Diario del Junior',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-6 py-12 md:px-12">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8">
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Home
        </Link>

        <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: February 2026</p>

        <div className="prose prose-invert max-w-none space-y-6 text-muted-foreground">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">About This Project</h2>
            <p>
              Diario del Junior is a personal, educational project created by an independent content creator. 
              It&apos;s an interactive map where you can explore procedurally generated characters. 
              This is not a commercial service or a company — it&apos;s an experimental project shared for entertainment and learning purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">How It Works</h2>
            <p>
              Characters are automatically generated using a procedural algorithm based on public usernames. 
              The same username will always produce the same character. Characters are for viewing only — they cannot be downloaded or exported.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">Fictional Characters</h2>
            <p>
              All characters displayed are entirely fictional and generated by an algorithm. 
              Any resemblance to real persons, living or dead, is purely coincidental. 
              Characters do not represent, endorse, or reflect any real individuals.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">Acceptable Use</h2>
            <p>When using this service, you agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use bots, scrapers, or automated tools to access the service</li>
              <li>Attempt to reverse engineer the character generation algorithm</li>
              <li>Mass-download or extract content from the service</li>
              <li>Interfere with the proper functioning of the service</li>
              <li>Use the service for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">Intellectual Property</h2>
            <p>
              The character generation algorithm, visual designs, and the service itself are original creations owned by the project author. 
              You may view characters on the platform, but you may not reproduce, distribute, or create derivative works without permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">No Warranties</h2>
            <p>
              This project is provided &quot;as is&quot; for entertainment purposes. 
              There are no guarantees of uptime, availability, or that the service will remain unchanged. 
              The project may evolve, change features, or be discontinued at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, the creator shall not be liable for any damages arising from the use of this service. 
              Use at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">Changes</h2>
            <p>
              These terms may be updated occasionally. Significant changes will be reflected in the &quot;Last updated&quot; date above. 
              Continued use of the service constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">Contact</h2>
            <p>
              Questions? Reach out through my social media channels.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
